%% RCbenchmark Multi-Configuration Motor-Log Comparison Plotter
%
% Allows multiple motor/propeller configurations to be compared.
%
% Each configuration may contain one or more CSV log files.
%
% Creates comparison figures for:
%   1. ESC Command vs Time
%   2. Thrust vs ESC Command
%   3. Current vs ESC Command
%   4. RPM vs ESC Command
%   5. Thrust Efficiency vs ESC Command
%   6. Thrust vs Current
%
% Each configuration is assigned a consistent colour across all figures.

clear;
clc;
close all;

%% ========================================================================
% Global formatting
% =========================================================================

set(groot, 'defaultTextInterpreter', 'latex');
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');

markerSize   = 10;
fontSize     = 16;
titleSize    = 22;
subtitleSize = 11;
legendSize   = 12;


%% ========================================================================
% Ask how many configurations are being compared
% =========================================================================

answer = inputdlg( ...
    {'Number of configurations to compare:'}, ...
    'Configuration Setup', ...
    [1 40], ...
    {'2'});

if isempty(answer)
    disp('Input cancelled.');
    return;
end

nConfigs = str2double(answer{1});

if ~isfinite(nConfigs) || ...
        nConfigs < 1 || ...
        mod(nConfigs,1) ~= 0

    error('Number of configurations must be a positive integer.');

end


%% ========================================================================
% Define configurations and select CSV files
% =========================================================================

configs = struct([]);

for c = 1:nConfigs

    fprintf('\n========================================\n');
    fprintf('CONFIGURATION %d OF %d\n', c, nConfigs);
    fprintf('========================================\n');

    defaultName = sprintf('Configuration %d', c);

    answer = inputdlg( ...
    { ...
    'Motor description:', ...
    'Propeller description:', ...
    'Legend name (leave blank to generate automatically):' ...
    }, ...
    sprintf('Configuration %d', c), ...
    [1 60; 1 60; 1 60], ...
    { ...
    '', ...
    '', ...
    '' ...
    });

    if isempty(answer)
        disp('Input cancelled.');
        return;
    end

    motorDescription = strtrim(answer{1});
    propDescription  = strtrim(answer{2});
    configName       = strtrim(answer{3});

    % Automatically generate legend name if none was entered
    if isempty(configName)

        if ~isempty(motorDescription) && ~isempty(propDescription)

            configName = sprintf( ...
                '%s + %s', ...
                motorDescription, ...
                propDescription);

        elseif ~isempty(motorDescription)

            configName = motorDescription;

        elseif ~isempty(propDescription)

            configName = propDescription;

        else

            configName = defaultName;

        end
    end


    %% Select one or more CSV files for this configuration

    [fileNames, filePath] = uigetfile( ...
        {'*.csv', 'CSV files (*.csv)'}, ...
        sprintf('Select CSV files for: %s', configName), ...
        'MultiSelect', 'on');

    if isequal(fileNames, 0)

        fprintf('No files selected for configuration %d.\n', c);
        return;

    end

    % uigetfile returns a character vector when only one file is selected
    if ischar(fileNames)
        fileNames = {fileNames};
    end

    configs(c).name      = configName;
    configs(c).motor     = motorDescription;
    configs(c).propeller = propDescription;
    configs(c).files     = cell(size(fileNames));
    configs(c).tables    = cell(size(fileNames));


    %% Load selected CSV files

    for f = 1:numel(fileNames)

        dataFile = fullfile(filePath, fileNames{f});

        fprintf('Loading: %s\n', dataFile);

        T = readtable( ...
            dataFile, ...
            'VariableNamingRule', 'preserve');

        configs(c).files{f}  = dataFile;
        configs(c).tables{f} = T;

        fprintf('    Samples: %d\n', height(T));

    end

    fprintf('\nConfiguration: %s\n', configName);
    fprintf('Motor:         %s\n', motorDescription);
    fprintf('Propeller:     %s\n', propDescription);
    fprintf('CSV files:     %d\n', numel(fileNames));

end


%% ========================================================================
% Assign one colour to each configuration
% =========================================================================

colors = lines(nConfigs);


%% ========================================================================
% Column aliases
% =========================================================================

timeAliases = { ...
    'Time (s)', ...
    'Time'};

escAliases = { ...
    'ESC signal (µs)', ...
    'ESC Signal (µs)', ...
    'ESC signal (us)', ...
    'ESC Signal (us)'};

thrustAliases = { ...
    'Thrust (kgf)', ...
    'Thrust (kg)'};

currentAliases = { ...
    'Current (A)', ...
    'Motor Current (A)'};

rpmAliases = { ...
    'Motor Electrical Speed (RPM)', ...
    'Motor Optical Speed (RPM)', ...
    'Motor Speed (RPM)', ...
    'RPM'};

efficiencyAliases = { ...
    'Overall Efficiency (kgf/W)', ...
    'Overall Efficiency (g/W)', ...
    'Efficiency (kgf/W)', ...
    'Efficiency (g/W)'};


%% ========================================================================
% Common subtitle
% =========================================================================

subtitleText = sprintf( ...
    '$\\mathrm{%d~Configurations~Compared}$', ...
    nConfigs);


%% ========================================================================
% ESC Command vs Time
% =========================================================================

plotTimeComparison( ...
    configs, ...
    colors, ...
    timeAliases, ...
    escAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    '$t\;(\mathrm{s})$', ...
    '$\mathrm{ESC\ Command\ Pulse\ Width}\;(\mu\mathrm{s})$', ...
    '$\mathrm{ESC\ Command\ Pulse\ Width\ vs.\ Time}$', ...
    subtitleText, ...
    'ESC Signal vs Time');


%% ========================================================================
% Thrust vs ESC Command
% =========================================================================

plotXYComparison( ...
    configs, ...
    colors, ...
    escAliases, ...
    thrustAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    '$\mathrm{ESC\ Command\ Pulse\ Width}\;(\mu\mathrm{s})$', ...
    '$T\;(\mathrm{kg_f})$', ...
    '$\mathrm{Static\ Thrust\ vs.\ ESC\ Command}$', ...
    subtitleText, ...
    'Thrust vs ESC Signal');


%% ========================================================================
% Current vs ESC Command
% =========================================================================

plotXYComparison( ...
    configs, ...
    colors, ...
    escAliases, ...
    currentAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    '$\mathrm{ESC\ Command\ Pulse\ Width}\;(\mu\mathrm{s})$', ...
    '$I\;(\mathrm{A})$', ...
    '$\mathrm{Motor\ Current\ vs.\ ESC\ Command}$', ...
    subtitleText, ...
    'Current vs ESC Signal');


%% ========================================================================
% RPM vs ESC Command
% =========================================================================

plotXYComparison( ...
    configs, ...
    colors, ...
    escAliases, ...
    rpmAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    '$\mathrm{ESC\ Command\ Pulse\ Width}\;(\mu\mathrm{s})$', ...
    '$n\;(\mathrm{RPM})$', ...
    '$\mathrm{Motor\ Speed\ vs.\ ESC\ Command}$', ...
    subtitleText, ...
    'RPM vs ESC Signal');


%% ========================================================================
% Thrust Efficiency vs ESC Command
%
% All efficiency data are converted to kgf/W before plotting.
% =========================================================================

plotEfficiencyComparison( ...
    configs, ...
    colors, ...
    escAliases, ...
    efficiencyAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    '$\mathrm{ESC\ Command\ Pulse\ Width}\;(\mu\mathrm{s})$', ...
    '$T/P_{\mathrm{elec}}\;(\mathrm{kg_f/W})$', ...
    '$\mathrm{Thrust\ Efficiency\ vs.\ ESC\ Command}$', ...
    subtitleText, ...
    'Efficiency vs ESC Signal');


%% ========================================================================
% Thrust vs Current
% =========================================================================

plotXYComparison( ...
    configs, ...
    colors, ...
    currentAliases, ...
    thrustAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    '$I\;(\mathrm{A})$', ...
    '$T\;(\mathrm{kg_f})$', ...
    '$\mathrm{Static\ Thrust\ vs.\ Motor\ Current}$', ...
    subtitleText, ...
    'Thrust vs Current');


%% ========================================================================
% Summary
% =========================================================================

fprintf('\n========================================\n');
fprintf('PLOTTING COMPLETE\n');
fprintf('========================================\n');

for c = 1:nConfigs

    fprintf( ...
        '%d: %s (%d CSV files)\n', ...
        c, ...
        configs(c).name, ...
        numel(configs(c).files));

end


%% ========================================================================
% Helper Functions
% ========================================================================


function plotXYComparison( ...
    configs, ...
    colors, ...
    xAliases, ...
    yAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    xLabelText, ...
    yLabelText, ...
    mainTitle, ...
    subtitleText, ...
    figureName)

% PLOTXYCOMPARISON
% Pools all valid data from the CSV files belonging to each configuration
% and plots one scatter series per configuration.

    fig = figure( ...
        'Color', 'w', ...
        'Name', figureName);

    ax = axes(fig);

    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');

    hasData = false;

    for c = 1:numel(configs)

        xAll = [];
        yAll = [];

        for f = 1:numel(configs(c).tables)

            T = configs(c).tables{f};

            xName = findColumn(T, xAliases);
            yName = findColumn(T, yAliases);

            if isempty(xName) || isempty(yName)
                continue;
            end

            x = convertToNumeric(T.(xName));
            y = convertToNumeric(T.(yName));

            idx = isfinite(x) & isfinite(y);

            xAll = [xAll; x(idx)]; %#ok<AGROW>
            yAll = [yAll; y(idx)]; %#ok<AGROW>

        end

        if ~isempty(xAll)

            scatter( ...
                ax, ...
                xAll, ...
                yAll, ...
                markerSize, ...
                'filled', ...
                'MarkerFaceColor', colors(c,:), ...
                'MarkerEdgeColor', colors(c,:), ...
                'DisplayName', escapeLatex(configs(c).name));

            hasData = true;

        else

            fprintf( ...
                'No valid data found for "%s" in figure "%s".\n', ...
                configs(c).name, ...
                figureName);

        end

    end


    if ~hasData

        close(fig);

        fprintf( ...
            'Skipping "%s": no valid data were found.\n', ...
            figureName);

        return;

    end


    xlabel( ...
        ax, ...
        xLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', fontSize);

    ylabel( ...
        ax, ...
        yLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', fontSize);

    set( ...
        ax, ...
        'FontSize', fontSize, ...
        'TickLabelInterpreter', 'latex');

    addPlotTitles( ...
        ax, ...
        mainTitle, ...
        subtitleText, ...
        titleSize, ...
        subtitleSize);

    legend( ...
        ax, ...
        'show', ...
        'Location', 'best', ...
        'Interpreter', 'latex', ...
        'FontSize', legendSize);

    hold(ax, 'off');

end


function plotTimeComparison( ...
    configs, ...
    colors, ...
    timeAliases, ...
    escAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    xLabelText, ...
    yLabelText, ...
    mainTitle, ...
    subtitleText, ...
    figureName)

% PLOTTIMECOMPARISON
%
% If multiple CSV files belong to one configuration, each file is shifted
% in time so that it begins after the preceding file.
%
% This avoids multiple independent logs all starting at t = 0.

    fig = figure( ...
        'Color', 'w', ...
        'Name', figureName);

    ax = axes(fig);

    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');

    hasData = false;

    for c = 1:numel(configs)

        timeAll = [];
        escAll  = [];

        runningEndTime = 0;

        for f = 1:numel(configs(c).tables)

            T = configs(c).tables{f};

            timeName = findColumn(T, timeAliases);
            escName  = findColumn(T, escAliases);

            if isempty(timeName) || isempty(escName)
                continue;
            end

            time = convertToNumeric(T.(timeName));
            esc  = convertToNumeric(T.(escName));

            idx = isfinite(time) & isfinite(esc);

            time = time(idx);
            esc  = esc(idx);

            if isempty(time)
                continue;
            end

            % Make each individual log begin at t = 0
            time = time - time(1);

            % Estimate sample interval
            dtVector = diff(time);
            dtVector = dtVector(isfinite(dtVector) & dtVector > 0);

            if isempty(dtVector)

                dt = 0;

            else

                dt = median(dtVector);

            end

            % Shift subsequent files to continue after previous log
            if ~isempty(timeAll)

                time = time + runningEndTime + dt;

            end

            timeAll = [timeAll; time]; %#ok<AGROW>
            escAll  = [escAll; esc];   %#ok<AGROW>

            runningEndTime = timeAll(end);

        end


        if ~isempty(timeAll)

            scatter( ...
                ax, ...
                timeAll, ...
                escAll, ...
                markerSize, ...
                'filled', ...
                'MarkerFaceColor', colors(c,:), ...
                'MarkerEdgeColor', colors(c,:), ...
                'DisplayName', escapeLatex(configs(c).name));

            hasData = true;

        end

    end


    if ~hasData

        close(fig);

        fprintf( ...
            'Skipping "%s": no valid data were found.\n', ...
            figureName);

        return;

    end


    xlabel( ...
        ax, ...
        xLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', fontSize);

    ylabel( ...
        ax, ...
        yLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', fontSize);

    set( ...
        ax, ...
        'FontSize', fontSize, ...
        'TickLabelInterpreter', 'latex');

    addPlotTitles( ...
        ax, ...
        mainTitle, ...
        subtitleText, ...
        titleSize, ...
        subtitleSize);

    legend( ...
        ax, ...
        'show', ...
        'Location', 'best', ...
        'Interpreter', 'latex', ...
        'FontSize', legendSize);

    hold(ax, 'off');

end


function plotEfficiencyComparison( ...
    configs, ...
    colors, ...
    escAliases, ...
    efficiencyAliases, ...
    markerSize, ...
    fontSize, ...
    titleSize, ...
    subtitleSize, ...
    legendSize, ...
    xLabelText, ...
    yLabelText, ...
    mainTitle, ...
    subtitleText, ...
    figureName)

% PLOTEFFICIENCYCOMPARISON
%
% Efficiency is converted to kgf/W before comparison.
%
% If input is g/W:
%
%       kgf/W = (g/W) / 1000

    fig = figure( ...
        'Color', 'w', ...
        'Name', figureName);

    ax = axes(fig);

    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');

    hasData = false;

    for c = 1:numel(configs)

        escAll = [];
        effAll = [];

        for f = 1:numel(configs(c).tables)

            T = configs(c).tables{f};

            escName = findColumn(T, escAliases);
            effName = findColumn(T, efficiencyAliases);

            if isempty(escName) || isempty(effName)
                continue;
            end

            esc = convertToNumeric(T.(escName));
            eff = convertToNumeric(T.(effName));

            % Convert g/W to kgf/W
            lowerName = lower(effName);

            if contains(lowerName, 'g/w') && ...
                    ~contains(lowerName, 'kgf/w')

                eff = eff ./ 1000;

            end

            idx = isfinite(esc) & isfinite(eff);

            escAll = [escAll; esc(idx)]; %#ok<AGROW>
            effAll = [effAll; eff(idx)]; %#ok<AGROW>

        end


        if ~isempty(escAll)

            scatter( ...
                ax, ...
                escAll, ...
                effAll, ...
                markerSize, ...
                'filled', ...
                'MarkerFaceColor', colors(c,:), ...
                'MarkerEdgeColor', colors(c,:), ...
                'DisplayName', escapeLatex(configs(c).name));

            hasData = true;

        end

    end


    if ~hasData

        close(fig);

        fprintf( ...
            'Skipping "%s": no valid data were found.\n', ...
            figureName);

        return;

    end


    xlabel( ...
        ax, ...
        xLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', fontSize);

    ylabel( ...
        ax, ...
        yLabelText, ...
        'Interpreter', 'latex', ...
        'FontSize', fontSize);

    set( ...
        ax, ...
        'FontSize', fontSize, ...
        'TickLabelInterpreter', 'latex');

    addPlotTitles( ...
        ax, ...
        mainTitle, ...
        subtitleText, ...
        titleSize, ...
        subtitleSize);

    legend( ...
        ax, ...
        'show', ...
        'Location', 'best', ...
        'Interpreter', 'latex', ...
        'FontSize', legendSize);

    hold(ax, 'off');

end


function name = findColumn(T, aliases)
% FINDCOLUMN
% Finds a matching table column from a list of possible names.

    variableNames = T.Properties.VariableNames;

    name = '';

    % Exact match first
    for i = 1:numel(aliases)

        idx = strcmp(variableNames, aliases{i});

        if any(idx)

            name = variableNames{find(idx,1)};
            return;

        end

    end

    % Case-insensitive match
    for i = 1:numel(aliases)

        idx = strcmpi(variableNames, aliases{i});

        if any(idx)

            name = variableNames{find(idx,1)};
            return;

        end

    end

end


function data = convertToNumeric(data)
% CONVERTTONUMERIC
% Ensures imported columns are numeric column vectors.

    if isnumeric(data) || islogical(data)

        data = double(data);

    else

        data = str2double(string(data));

    end

    data = data(:);

end


function txt = escapeLatex(txt)
% ESCAPELATEX
% Prepares user-entered text for MATLAB's LaTeX interpreter.

    txt = strrep(txt, '\', '\textbackslash ');
    txt = strrep(txt, '_', '\_');
    txt = strrep(txt, '%', '\%');
    txt = strrep(txt, '&', '\&');
    txt = strrep(txt, '#', '\#');
    txt = strrep(txt, '$', '\$');
    txt = strrep(txt, '{', '\{');
    txt = strrep(txt, '}', '\}');

    % Preserve spaces in LaTeX math mode
    txt = strrep(txt, ' ', '~');

end


function addPlotTitles( ...
    ax, ...
    mainTitle, ...
    secondaryTitle, ...
    titleSize, ...
    subtitleSize)

% ADDPLOTTITLES
% Adds consistent main and secondary titles.

    ax.TitleFontSizeMultiplier = 1;

    hTitle = title( ...
        ax, ...
        mainTitle, ...
        'Interpreter', 'latex', ...
        'FontWeight', 'bold');

    hSubtitle = subtitle( ...
        ax, ...
        secondaryTitle, ...
        'Interpreter', 'latex', ...
        'FontWeight', 'normal');

    hTitle.FontSize    = titleSize;
    hSubtitle.FontSize = subtitleSize;

end